# 指定语言及版本
language: node_js
node_js:
  - "10"

# 安装项目包
install:
  - npm install
  - npm add node-sass

# 运行脚本
script:
  - npm run docs:build

# 自动化编译推送GitHub
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $travis_ci # travis setting 中的环境变量 GITHUB_TOKEN
  local-dir: ./web/my-components-librarys # 根据情况自定义到静态文件输出目录
  target-branch: gh-pages # 构建后的静态资源提交到这个分支
  verbose: true
  on:
    branch: master # 触发自动化部署的分支
